/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import formAdmin.FormNoviAdmin;
import formAdmin.FormPretragaAdmina;
import formPizza.FormNovaPica;
import formPizza.FormPretragaPizze;
import controller.ClientController;
import domain.Admin;
import domain.Racun;
import domain.Pizza;
import domain.StavkaRacuna;
import domain.VrstaPizze;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelStavke;
import session.Session;

/**
 *
 * @author Korisnik
 */
public class MainForm extends javax.swing.JFrame {

    Admin a;
    int ukupnaKolicina;
    double ukupnaCena;
    double rabat;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.a = Session.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani admin: " + a);
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbPizza = new javax.swing.JComboBox();
        txtKolicina = new javax.swing.JFormattedTextField();
        txtCenaStavke = new javax.swing.JFormattedTextField();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        txtCena = new javax.swing.JTextField();
        lblRabat = new javax.swing.JLabel();
        txtKonacnaCena = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        lblUlogovani = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNoviAdmin = new javax.swing.JMenuItem();
        miPretragaAdmina = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miUnosPizza = new javax.swing.JMenuItem();
        miPretragaPizza = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzeria");
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos računa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setText("Cena:");

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setText("Količinski rabat:");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setText("Konačna cena:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos stavki računa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 2, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setText("Pizza:");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setText("Količina:");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setText("Cena stavke:");

        cmbPizza.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        cmbPizza.setForeground(new java.awt.Color(255, 102, 0));
        cmbPizza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPizza.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPizzaItemStateChanged(evt);
            }
        });

        txtKolicina.setForeground(new java.awt.Color(255, 102, 0));
        txtKolicina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtKolicina.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtKolicina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKolicinaKeyReleased(evt);
            }
        });

        txtCenaStavke.setForeground(new java.awt.Color(255, 102, 0));
        txtCenaStavke.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCenaStavke.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        btnDodaj.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnDodaj.setForeground(new java.awt.Color(255, 102, 0));
        btnDodaj.setText("Dodaj stavku");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnObrisi.setForeground(new java.awt.Color(255, 102, 0));
        btnObrisi.setText("Obriši stavku");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        tblStavke.setForeground(new java.awt.Color(255, 102, 0));
        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStavke.setGridColor(new java.awt.Color(255, 102, 0));
        tblStavke.setSelectionBackground(new java.awt.Color(255, 204, 102));
        tblStavke.setSelectionForeground(new java.awt.Color(255, 102, 0));
        jScrollPane1.setViewportView(tblStavke);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCenaStavke)
                            .addComponent(txtKolicina)
                            .addComponent(cmbPizza, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCenaStavke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        txtCena.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCena.setForeground(new java.awt.Color(255, 102, 0));

        lblRabat.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblRabat.setForeground(new java.awt.Color(255, 102, 0));
        lblRabat.setText("0%");

        txtKonacnaCena.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtKonacnaCena.setForeground(new java.awt.Color(255, 102, 0));

        btnSacuvaj.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnSacuvaj.setForeground(new java.awt.Color(255, 102, 0));
        btnSacuvaj.setText("Sačuvaj račun");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(89, 89, 89)
                                .addComponent(txtCena))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKonacnaCena)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblRabat, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblRabat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKonacnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        lblUlogovani.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        lblUlogovani.setForeground(new java.awt.Color(255, 102, 0));
        lblUlogovani.setText("Ulogovani");

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 255));

        jMenu6.setText("Admin");
        jMenu6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        miNoviAdmin.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        miNoviAdmin.setText("Novi admin");
        miNoviAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviAdminActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviAdmin);

        miPretragaAdmina.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        miPretragaAdmina.setText("Pretraga admina");
        miPretragaAdmina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaAdminaActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaAdmina);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Pizza");
        jMenu7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        miUnosPizza.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        miUnosPizza.setText("Unos pizze");
        miUnosPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnosPizzaActionPerformed(evt);
            }
        });
        jMenu7.add(miUnosPizza);

        miPretragaPizza.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        miPretragaPizza.setText("Pretraga pizze");
        miPretragaPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaPizzaActionPerformed(evt);
            }
        });
        jMenu7.add(miPretragaPizza);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Odjava");
        jMenu8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N

        miOdjava.setText("Odjava sa sistema");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu8.add(miOdjava);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviAdminActionPerformed
        if (a.getAdminID() == 1) {
            new FormNoviAdmin(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Samo glavni admin ima pristup"
                    + " ovoj operaciji!");
        }

    }//GEN-LAST:event_miNoviAdminActionPerformed

    private void miPretragaAdminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaAdminaActionPerformed
        if (a.getAdminID() == 1) {
            new FormPretragaAdmina(this, true).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Samo glavni admin ima pristup"
                    + " ovoj operaciji!");
        }
    }//GEN-LAST:event_miPretragaAdminaActionPerformed

    private void miPretragaPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaPizzaActionPerformed
        new FormPretragaPizze(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaPizzaActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            new LoginForma().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_miOdjavaActionPerformed

    private void miUnosPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnosPizzaActionPerformed
        new FormNovaPica(this, true).setVisible(true);
    }//GEN-LAST:event_miUnosPizzaActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        if (txtKolicina.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti kolicinu!");
            return;
        }

        Pizza s = (Pizza) cmbPizza.getSelectedItem();
        int kolicina = Integer.parseInt(txtKolicina.getText());
        double cenaStavke = Double.parseDouble(txtCenaStavke.getText());

        StavkaRacuna sr = new StavkaRacuna(null, -1, kolicina, cenaStavke, s);

        TableModelStavke tm = (TableModelStavke) tblStavke.getModel();

        tm.dodajStavku(sr);

        ukupnaCena = tm.getUkupnaCena();
        ukupnaKolicina = tm.getUkupnaKolicina();

        txtCena.setText(String.valueOf(ukupnaCena));

        if (ukupnaKolicina < 10) {
            lblRabat.setText("0%");
            rabat = 0;
            txtKonacnaCena.setText(String.valueOf(ukupnaCena));
        }

        if (ukupnaKolicina >= 10 && ukupnaKolicina < 20) {
            lblRabat.setText("10%");
            rabat = 10;
            txtKonacnaCena.setText(String.valueOf(ukupnaCena * 0.9));
        }

        if (ukupnaKolicina >= 20) {
            lblRabat.setText("20%");
            rabat = 20;
            txtKonacnaCena.setText(String.valueOf(ukupnaCena * 0.8));
        }


    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int row = tblStavke.getSelectedRow();

        if (row >= 0) {
            TableModelStavke tm = (TableModelStavke) tblStavke.getModel();
            tm.obrisiStavku(row);

            ukupnaCena = tm.getUkupnaCena();
            ukupnaKolicina = tm.getUkupnaKolicina();

            txtCena.setText(String.valueOf(ukupnaCena));

            if (ukupnaKolicina < 10) {
                lblRabat.setText("0%");
                rabat = 0;
                txtKonacnaCena.setText(String.valueOf(ukupnaCena));
            }

            if (ukupnaKolicina >= 10 && ukupnaKolicina < 20) {
                lblRabat.setText("10%");
                rabat = 10;
                txtKonacnaCena.setText(String.valueOf(ukupnaCena * 0.9));
            }

            if (ukupnaKolicina >= 20) {
                lblRabat.setText("20%");
                rabat = 20;
                txtKonacnaCena.setText(String.valueOf(ukupnaCena * 0.8));
            }

        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void txtKolicinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKolicinaKeyReleased

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {

            if (txtKolicina.getText().isEmpty()) {
                txtKolicina.setText("");
                return;
            }

            Pizza s = (Pizza) cmbPizza.getSelectedItem();
            int kolicina = Integer.parseInt(txtKolicina.getText());

            txtCenaStavke.setText(String.valueOf(s.getCena() * kolicina));

        } else {
            txtKolicina.setText("");
            txtCenaStavke.setText("0.00");
        }

    }//GEN-LAST:event_txtKolicinaKeyReleased

    private void cmbPizzaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPizzaItemStateChanged

        if (cmbPizza.getSelectedItem() != null && !txtKolicina.getText().isEmpty()) {
            Pizza s = (Pizza) cmbPizza.getSelectedItem();
            int kolicina = Integer.parseInt(txtKolicina.getText());
            txtCenaStavke.setText(String.valueOf(s.getCena() * kolicina));
        }

    }//GEN-LAST:event_cmbPizzaItemStateChanged

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {
            TableModelStavke tm = (TableModelStavke) tblStavke.getModel();
            double konacnaCena = Double.parseDouble(txtKonacnaCena.getText());

            Racun r = new Racun(null, new Date(), ukupnaCena, rabat, konacnaCena, a, tm.getLista());

            ClientController.getInstance().addRacun(r);
            resetujFormu();
            JOptionPane.showMessageDialog(this, "Uspešno sačuvan račun!");
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbPizza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRabat;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNoviAdmin;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPretragaAdmina;
    private javax.swing.JMenuItem miPretragaPizza;
    private javax.swing.JMenuItem miUnosPizza;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtCena;
    private javax.swing.JFormattedTextField txtCenaStavke;
    private javax.swing.JFormattedTextField txtKolicina;
    private javax.swing.JTextField txtKonacnaCena;
    // End of variables declaration//GEN-END:variables

    public void popuniPizze() {
        try {
            ArrayList<Pizza> pice = ClientController.getInstance().getAllPizza();

            cmbPizza.removeAllItems();

            for (Pizza pizza : pice) {
                cmbPizza.addItem(pizza);
            }

        } catch (Exception ex) {
            Logger.getLogger(FormNovaPica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void srediFormu() {
        popuniPizze();
        tblStavke.setModel(new TableModelStavke());
        txtCenaStavke.setEditable(false);
        txtCena.setEditable(false);
        txtKonacnaCena.setEditable(false);
        txtCenaStavke.setText("0.00");
        txtCena.setText("0.00");
        txtKonacnaCena.setText("0.00");
    }

    private void resetujFormu() {
        txtCenaStavke.setText("0.00");
        txtCena.setText("0.00");
        txtKonacnaCena.setText("0.00");
        lblRabat.setText("0%");
        txtKolicina.setText("");
        TableModelStavke tm = (TableModelStavke) tblStavke.getModel();
        tm.getLista().clear();
        tm.fireTableDataChanged();
        ukupnaCena = 0;
        ukupnaKolicina = 0;
        rabat = 0;
    }

}
